create table employees(
id serial primary key,
employee_name varchar(50) not null
)

insert into employees(id, employee_name)
values (default, 'Дмитрий Родин'),
(default,'Матвей Галкин'),
(default,'Никита Поляков'),
(default,'Марк Кулаков'),
(default,'Ксения Артемова'),
(default,'Мария Лаврова'),
(default,'Диана Наумова'),
(default,'Александр Калашников'),
(default,'Дмитрий Степанов'),
(default,'Александр Фадеев'),
(default,'Ольга Селиванова'),
(default,'Таисия Кузьмина'),
(default,'Илья Мешков'),
(default,'Кирилл Поляков'),
(default,'Арина Сальникова'),
(default,'Артём Кузьмин'),
(default,'Амина Куликова'),
(default,'Валерия Грачева'),
(default,'Максим Кузнецов'),
(default,'Дмитрий Громов'),
(default,'Артём Королев'),
(default,'Валерия Сазонова'),
(default,'Андрей Князев'),
(default,'Екатерина Плотникова'),
(default,'Марк Маркин'),
(default,'Иван Колосов'),
(default,'Анна Сухарева'),
(default,'Марианна Суворова'),
(default,'Роман Иванов'),
(default,'Анастасия Белоусова'),
(default,'Владимир Медведев'),
(default,'Милана Крылова'),
(default,'Владимир Горлов'),
(default,'Фёдор Коровин'),
(default,'Егор Горбачев'),
(default,'Савелий Куликов'),
(default,'Лев Федоров'),
(default,'Всеволод Комаров'),
(default,'Мария Черепанова'),
(default,'София Козлова'),
(default,'Фёдор Фролов'),
(default,'Георгий Титов'),
(default,'Дарья Свиридова'),
(default,'Савелий Дьяков'),
(default,'Алиса Беликова'),
(default,'София Макарова'),
(default,'Ярослав Самойлов'),
(default,'Ксения Осипова'),
(default,'Ярослав Щербаков'),
(default,'Лев Новиков'),
(default,'Арина Давыдова'),
(default,'Илья Жданов'),
(default,'Мария Кузина'),
(default,'Богдан Никифоров'),
(default,'Максим Орехов'),
(default,'Александра Иванова'),
(default,'София Винокурова'),
(default,'Аделина Кузьмина'),
(default,'Таисия Мартынова'),
(default,'Полина Голованова'),
(default,'Захар Григорьев'),
(default,'Алексей Архипов'),
(default,'Мирослава Муратова'),
(default,'Виктория Серебрякова'),
(default,'Серафима Коровина'),
(default,'Святослав Иванов'),
(default,'Никита Агеев'),
(default,'Екатерина Зайцева'),
(default,'Варвара Маркина'),
(default,'Ксения Бирюкова');

create table salary(
id serial PRIMARY KEY,
monthly_salary int not null
)

insert into salary (id, monthly_salary)
values(default, 1000),
(default, 1100),
(default, 1200),
(default, 1300),
(default, 1400),
(default, 1500),
(default, 1600),
(default, 1700),
(default, 1800),
(default, 1900),
(default, 2000),
(default, 2100),
(default, 2200),
(default, 2300),
(default, 2400),
(default, 2500);

create table employee_salary(
id serial primary key,
employee_id int not null unique,
salary_id int not null
)

select * from employee_salary

insert into employee_salary(id, employee_id, salary_id)
values(default, 300, 1),
(default, 301, 2),
(default, 302, 3),
(default, 303, 4),
(default, 304, 5),
(default, 305, 6),
(default, 306, 7),
(default, 307, 8),
(default, 308, 9),
(default, 309, 10),
(default, 70, 11),
(default, 69, 12),
(default, 68, 13),
(default, 67, 14),
(default, 66, 15),
(default, 65, 16),
(default, 64, 1),
(default, 63, 2),
(default, 62, 3),
(default, 61, 4),
(default, 60, 5),
(default, 59, 6),
(default, 58, 7),
(default, 57, 8),
(default, 56, 9),
(default, 55, 10),
(default, 54, 11),
(default, 53, 12),
(default, 52, 13),
(default, 51, 14),
(default, 50, 15),
(default, 49, 16),
(default, 48, 1),
(default, 47, 2),
(default, 46, 3),
(default, 45, 4),
(default, 44, 5),
(default, 43, 6),
(default, 42, 7),
(default, 41, 8);
	
create table roles(
id serial primary key,
role_name int not null unique
)

alter table roles
alter column role_name type varchar(30)

insert into roles(id, role_name)
values(default, 'Junior Python developer'),
(default, 'Junior Java developer'),
(default, 'Junior JavaScript developer'),
(default, 'Junior Manual QA engineer'),
(default, 'Junior Automation QA engineer'),
(default, 'Sales manager'),
(default, 'CEO'),
(default, 'HR'),
(default, 'Designer'),
(default, 'Project Manager'),
(default, 'Middle Python developer'),
(default, 'Middle Java developer'),
(default, 'Middle JavaScript developer'),
(default, 'Middle Manual QA engineer'),
(default, 'Middle Automation QA engineer'),
(default, 'Senior Java developer'),
(default, 'Senior JavaScript developer'),
(default, 'Senior Manual QA engineer'),
(default, 'Senior Automation QA engineer'),
(default, 'Senior Python developer');

create table roles_employee(
id serial primary key,
employee_id int not null unique,
foreign key (employee_id)
		references employees(id),
role_id int not null,
foreign key (role_id)
		references roles(id)
)

insert into roles_employee(id, employee_id, role_id)
values (default, 40, 1),
		(default, 39, 2),
		(default, 38, 3),
		(default, 37, 4),
		(default, 36, 5),
		(default, 35, 6),
		(default, 34, 7),
		(default, 33, 8),
		(default, 32, 9),
		(default, 31, 10),
		(default, 30, 11),
		(default, 29, 12),
		(default, 28, 13),
		(default, 27, 14),
		(default, 26, 15),
		(default, 25, 16),
		(default, 24, 17),
		(default, 23, 18),
		(default, 22, 19),
		(default, 21, 20),
		(default, 20, 1),
		(default, 19, 2),
		(default, 18, 3),
		(default, 17, 4),
		(default, 16, 5),
		(default, 15, 6),
		(default, 14, 7),
		(default, 13, 8),
		(default, 12, 9),
		(default, 11, 10),
		(default, 10, 11),
		(default, 9, 12),
		(default, 8, 13),
		(default, 7, 14),
		(default, 6, 16),
		(default, 5, 17),
		(default, 4, 18),
		(default, 3, 19),
		(default, 2, 20);
	
select * from roles_employee